apiVersion: v1
kind: Service
metadata:
  name: stock-prediction-service
spec:
  type: LoadBalancer
  selector:
    app: stock-predictor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000